<a href="https://colab.research.google.com/github/Michael2004-ukpeh/ml-playground/blob/master/Feature_Engineering_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Engineering Task

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub as kh
import re
import os

## Import Kaggle Data

In [ ]:
data_path = kh.dataset_download("amruthayenikonda/dirty-dataset-to-practice-data-cleaning")
os.listdir(data_path)

Using Colab cache for faster access to the 'dirty-dataset-to-practice-data-cleaning' dataset.

['my_file (1).csv']

In [ ]:
file_name = data_path + "/my_file (1).csv"
df = pd.read_csv(file_name)
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [ ]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

Get info on dataframe

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

# Utility Functions

In [ ]:
# Remove references helper
def remove_refs(x):
    if pd.isna(x):
        return np.nan
    return re.sub(r"\[.*?\]", "", str(x))

# Clean Peak

In [ ]:
df["Peak"]

0         1
1         1
2      1[4]
3      2[7]
4      2[4]
5      2[4]
6     2[10]
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13    1[20]
14     2[c]
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
Name: Peak, dtype: object

In [ ]:
df["Peak"] = df["Peak"].apply(remove_refs).astype(float)
df["Peak"]

0     1.0
1     1.0
2     1.0
3     2.0
4     2.0
5     2.0
6     2.0
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    1.0
14    2.0
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: Peak, dtype: float64

# Clean All time peak

In [ ]:
df["All Time Peak"]= df['All Time Peak'].apply(remove_refs).astype(float)
df["All Time Peak"]

0      2.0
1      7.0
2      2.0
3     10.0
4      NaN
5     10.0
6      NaN
7      NaN
8      NaN
9      NaN
10     NaN
11    14.0
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
Name: All Time Peak, dtype: float64

# Clean Currency related Fields

In [ ]:
# Clean currency columns to remove dollar sign and commas
# \u00A is non-breaking space in pandas
currency_cols = [
    "Actual\u00A0gross",
    "Adjusted\u00A0gross (in 2022 dollars)",
    "Average gross"
]

for col in currency_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r"\[.*?\]", "", regex=True)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .astype(float)
    )

df[currency_cols]

    Actual gross  Adjusted gross (in 2022 dollars)  Average gross
0    780000000.0                       780000000.0     13928571.0
1    579800000.0                       579800000.0     10353571.0
2    411000000.0                       560622615.0      4835294.0
3    397300000.0                       454751555.0      2546795.0
4    345675146.0                       402844849.0      6522173.0
5    305158363.0                       388978496.0      3467709.0
6    280000000.0                       381932682.0      2137405.0
7    257600000.0                       257600000.0      6282927.0
8    256084556.0                       312258401.0      5226215.0
9    250400000.0                       309141878.0      2945882.0
10   229100000.0                       283202896.0      1735606.0
11   227400000.0                       295301479.0      1118227.0
12   204000000.0                       251856802.0      1350993.0
13   200000000.0                       299676265.0       615385.0
14   194000000.0                       281617035.0      3233333.0
15   184000000.0                       227452347.0      1295775.0
16   170000000.0                       213568571.0      1734694.0
17   169800000.0                       207046755.0      2070732.0
18   167700000.0                       204486106.0      1385950.0
19   150000000.0                       185423109.0      1744186.0

# Clean Text in Artist and Tour Title columns

In [ ]:
df["Artist"] = df["Artist"].apply(remove_refs)

df["Tour title"] = (
    df["Tour title"]
    .astype(str)
    .str.replace(r"\[.*?\]", "", regex=True)
    .str.replace("†", "", regex=False)
    .str.replace("‡", "", regex=False)
    .str.replace("*", "", regex=False)
    .str.strip()
)

df[["Artist", "Tour title"]]

          Artist                       Tour title
0   Taylor Swift                    The Eras Tour
1        Beyoncé           Renaissance World Tour
2        Madonna              Sticky & Sweet Tour
3           Pink      Beautiful Trauma World Tour
4   Taylor Swift          Reputation Stadium Tour
5        Madonna                    The MDNA Tour
6    Celine Dion        Taking Chances World Tour
7           Pink                  Summer Carnival
8        Beyoncé         The Formation World Tour
9   Taylor Swift              The 1989 World Tour
10       Beyoncé  The Mrs. Carter Show World Tour
11     Lady Gaga            The Monster Ball Tour
12    Katy Perry             Prismatic World Tour
13          Cher  Living Proof: The Farewell Tour
14       Madonna                 Confessions Tour
15          Pink        The Truth About Love Tour
16     Lady Gaga               Born This Way Ball
17       Madonna                 Rebel Heart Tour
18         Adele                  Adele Live 2016
19  Taylor Swift                     The Red Tour

# Clean Years column
By engineering, start date and end date by splitting the years

In [ ]:
df["Year(s)"]
# Feature engineer Year(s)
def split_years(x):
    if pd.isna(x):
        return pd.Series([np.nan, np.nan, np.nan])
    years = re.split("–|-", x)
    start = int(years[0])
    end = int(years[-1])
    return pd.Series([start, end, end - start + 1])

df[["start_year", "end_year", "tour_duration_years"]] = (
    df["Year(s)"].apply(split_years)
)
df[["start_year", "end_year", "tour_duration_years"]]

    start_year  end_year  tour_duration_years
0         2023      2024                    2
1         2023      2023                    1
2         2008      2009                    2
3         2018      2019                    2
4         2018      2018                    1
5         2012      2012                    1
6         2008      2009                    2
7         2023      2024                    2
8         2016      2016                    1
9         2015      2015                    1
10        2013      2014                    2
11        2009      2011                    3
12        2014      2015                    2
13        2002      2005                    4
14        2006      2006                    1
15        2013      2014                    2
16        2012      2013                    2
17        2015      2016                    2
18        2016      2017                    2
19        2013      2014                    2

# Make sure show columns are integers

In [ ]:
df["Shows"] = df["Shows"].astype(int)

# Remove ref and year(s) columns

In [ ]:
df.drop(columns=[ "Ref.", "Year(s)"], inplace=True)

# Clean Rank column, eliminating duplicate ranks by ranking revenue

In [ ]:
df = df.sort_values(
    by="Adjusted\u00A0gross (in 2022 dollars)",
    ascending=False
)

df["Rank"] = range(1, len(df) + 1)

# View Cleaned dataset

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      float64
 2   All Time Peak                     6 non-null      float64
 3   Actual gross                      20 non-null     float64
 4   Adjusted gross (in 2022 dollars)  20 non-null     float64
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Shows                             20 non-null     int64
 8   Average gross                     20 non-null     float64
 9   start_year                        20 non-null     int64
 10  end_year                          20 non-null     int64
 11  tour_duration_years               20 non-null     int64
dtypes: float64(5), int64(5), object(2)
memory usage: 2.0+ KB

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,start_year,end_year,tour_duration_years
0,1,1.0,2.0,780000000.0,780000000.0,Taylor Swift,The Eras Tour,56,13928571.0,2023,2024,2
1,2,1.0,7.0,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,56,10353571.0,2023,2023,1
2,3,1.0,2.0,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,85,4835294.0,2008,2009,2
3,4,2.0,10.0,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,156,2546795.0,2018,2019,2
4,5,2.0,NaN,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,53,6522173.0,2018,2018,1

In [ ]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,start_year,end_year,tour_duration_years
0,1,1.0,2.0,780000000.0,780000000.0,Taylor Swift,The Eras Tour,56,13928571.0,2023,2024,2
1,2,1.0,7.0,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,56,10353571.0,2023,2023,1
2,3,1.0,2.0,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,85,4835294.0,2008,2009,2
3,4,2.0,10.0,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,156,2546795.0,2018,2019,2
4,5,2.0,NaN,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,53,6522173.0,2018,2018,1
5,6,2.0,10.0,305158363.0,388978496.0,Madonna,The MDNA Tour,88,3467709.0,2012,2012,1
6,7,2.0,NaN,280000000.0,381932682.0,Celine Dion,Taking Chances World Tour,131,2137405.0,2008,2009,2
8,8,NaN,NaN,256084556.0,312258401.0,Beyoncé,The Formation World Tour,49,5226215.0,2016,2016,1
9,9,NaN,NaN,250400000.0,309141878.0,Taylor Swift,The 1989 World Tour,85,2945882.0,2015,2015,1
13,10,1.0,NaN,200000000.0,299676265.0,Cher,Living Proof: The Farewell Tour,325,615385.0,2002,2005,4
11,11,NaN,14.0,227400000.0,295301479.0,Lady Gaga,The Monster Ball Tour,203,1118227.0,2009,2011,3
10,12,NaN,NaN,229100000.0,283202896.0,Beyoncé,The Mrs. Carter Show World Tour,132,1735606.0,2013,2014,2
14,13,2.0,NaN,194000000.0,281617035.0,Madonna,Confessions Tour,60,3233333.0,2006,2006,1
7,14,NaN,NaN,257600000.0,257600000.0,Pink,Summer Carnival,41,6282927.0,2023,2024,2
12,15,NaN,NaN,204000000.0,251856802.0,Katy Perry,Prismatic World Tour,151,1350993.0,2014,2015,2
15,16,NaN,NaN,184000000.0,227452347.0,Pink,The Truth About Love Tour,142,1295775.0,2013,2014,2
16,17,NaN,NaN,170000000.0,213568571.0,Lady Gaga,Born This Way Ball,98,1734694.0,2012,2013,2
17,18,NaN,NaN,169800000.0,207046755.0,Madonna,Rebel Heart Tour,82,2070732.0,2015,2016,2
18,19,NaN,NaN,167700000.0,204486106.0,Adele,Adele Live 2016,121,1385950.0,2016,2017,2
19,20,NaN,NaN,150000000.0,185423109.0,Taylor Swift,The Red Tour,86,1744186.0,2013,2014,2

## Analyze Current Data State and Missing Values


Display `df.isnull().sum()` to identify remaining missing values.

In [ ]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Shows                                0
Average gross                        0
start_year                           0
end_year                             0
tour_duration_years                  0
dtype: int64

## Data Transformation Summary Table

| Column Name                        | Data Type   | Observed Issue                                            | Proposed Feature Engineering Steps                                                              |
|:-----------------------------------|:------------|:----------------------------------------------------------|:--------------------------------------------------------------------------------------------------|
| `Rank`                             | `int64`     | Duplicate values (original data)                          | Re-ranked based on `Adjusted gross (in 2022 dollars)` in descending order.                        |
| `Peak`                             | `float64`   | Contains references (e.g., `[4]`), `NaN` values           | Removed references (`[...]`), converted to `float`. Remaining `NaN` values.                     |
| `All Time Peak`                    | `float64`   | Contains references (e.g., `[2]`), `NaN` values           | Removed references (`[...]`), converted to `float`. Remaining `NaN` values.                     |
| `Actual gross`                     | `float64`   | Contains '$', ',', references (e.g., `[b]`), non-breaking space | Removed '$', ',', `[...]`, converted to `float`.                                                |
| `Adjusted gross (in 2022 dollars)` | `float64`   | Contains '$', ',', non-breaking space                   | Removed '$', ',', converted to `float`.                                                         |
| `Artist`                           | `object`    | Contains references (e.g., `[c]`)                         | Removed references (`[...]`).                                                                     |
| `Tour title`                       | `object`    | Contains references (e.g., `[4][a]`), `†`, `‡`, `*` symbols, leading/trailing spaces | Removed `[...], †, ‡, *`, then `strip()` leading/trailing spaces.                               |
| `Year(s)`                          | Dropped     | Year ranges (e.g., `2023–2024`)                           | Split into `start_year`, `end_year`, and `tour_duration_years`. Original column dropped.      |
| `Shows`                            | `int64`     | None explicit                                             | Ensured type is `int`.                                                                            |
| `Average gross`                    | `float64`   | Contains '$', ',', non-breaking space                   | Removed '$', ',', converted to `float`.                                                         |
| `Ref.`                             | Dropped     | Not relevant for analysis                                 | Dropped from the DataFrame.                                                                       |
| `start_year`                       | `int64`     | New feature                                               | Extracted starting year from `Year(s)`.                                                         |
| `end_year`                         | `int64`     | New feature                                               | Extracted ending year from `Year(s)`.                                                           |
| `tour_duration_years`              | `int64`     | New feature                                               | Calculated duration of the tour in years from `start_year` and `end_year`.                      |

## Implement Missing Values with Pandas


Use pandas to impute `NaN` values in the 'Peak' and 'All Time Peak' columns with their respective median values. Display `df.isnull().sum()` again to confirm no NaNs are left in these columns, and then display `df.head()` to show the cleaned DataFrame.

In [ ]:
df['Peak'].fillna(df['Peak'].median(), inplace=True)
df['All Time Peak'].fillna(df['All Time Peak'].median(), inplace=True)

df.isnull().sum()
df.head()

/tmp/ipython-input-2800895605.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Peak'].fillna(df['Peak'].median(), inplace=True)
/tmp/ipython-input-2800895605.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['All Time Peak'].fillna(df['All Time Peak'].median(), inplace=True)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,start_year,end_year,tour_duration_years
0,1,1.0,2.0,780000000.0,780000000.0,Taylor Swift,The Eras Tour,56,13928571.0,2023,2024,2
1,2,1.0,7.0,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,56,10353571.0,2023,2023,1
2,3,1.0,2.0,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,85,4835294.0,2008,2009,2
3,4,2.0,10.0,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,156,2546795.0,2018,2019,2
4,5,2.0,8.5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,53,6522173.0,2018,2018,1

# Implement Feature Engineering with Scikit-learn Pipelines

Identify numerical columns that are suitable for scaling and categorical columns for one-hot encoding. Create a `ColumnTransformer` to apply `StandardScaler` to numerical features ('Peak', 'All Time Peak', 'Shows', 'Average gross', 'start_year', 'end_year', 'tour_duration_years') and `OneHotEncoder` to the 'Artist' and 'Tour title' columns. Then, fit and transform the DataFrame to produce the final feature-engineered dataset.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd

numerical_cols = [
    'Rank',
    'Peak',
    'All Time Peak',
    'Shows',
    'Average gross',
    'start_year',
    'end_year',
    'tour_duration_years',
    'Actual\u00A0gross',
    'Adjusted\u00A0gross (in 2022 dollars)'
]
categorical_cols = ['Artist', 'Tour title']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ])

df_processed = preprocessor.fit_transform(df)
feature_names = preprocessor.get_feature_names_out()

df_final = pd.DataFrame(df_processed, columns=feature_names)

print(df_final.info())
df_final

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 39 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   num__Rank                                        20 non-null     float64
 1   num__Peak                                        20 non-null     float64
 2   num__All Time Peak                               20 non-null     float64
 3   num__Shows                                       20 non-null     float64
 4   num__Average gross                               20 non-null     float64
 5   num__start_year                                  20 non-null     float64
 6   num__end_year                                    20 non-null     float64
 7   num__tour_duration_years                         20 non-null     float64
 8   num__Actual gross                                20 non-null     float64
 9   num__Adjusted gross (in 2022 dollars)            20 non-null     float64
 10  cat__Artist_Adele                                20 non-null     float64
 11  cat__Artist_Beyoncé                              20 non-null     float64
 12  cat__Artist_Celine Dion                          20 non-null     float64
 13  cat__Artist_Cher                                 20 non-null     float64
 14  cat__Artist_Katy Perry                           20 non-null     float64
 15  cat__Artist_Lady Gaga                            20 non-null     float64
 16  cat__Artist_Madonna                              20 non-null     float64
 17  cat__Artist_Pink                                 20 non-null     float64
 18  cat__Artist_Taylor Swift                         20 non-null     float64
 19  cat__Tour title_Adele Live 2016                  20 non-null     float64
 20  cat__Tour title_Beautiful Trauma World Tour      20 non-null     float64
 21  cat__Tour title_Born This Way Ball               20 non-null     float64
 22  cat__Tour title_Confessions Tour                 20 non-null     float64
 23  cat__Tour title_Living Proof: The Farewell Tour  20 non-null     float64
 24  cat__Tour title_Prismatic World Tour             20 non-null     float64
 25  cat__Tour title_Rebel Heart Tour                 20 non-null     float64
 26  cat__Tour title_Renaissance World Tour           20 non-null     float64
 27  cat__Tour title_Reputation Stadium Tour          20 non-null     float64
 28  cat__Tour title_Sticky & Sweet Tour              20 non-null     float64
 29  cat__Tour title_Summer Carnival                  20 non-null     float64
 30  cat__Tour title_Taking Chances World Tour        20 non-null     float64
 31  cat__Tour title_The 1989 World Tour              20 non-null     float64
 32  cat__Tour title_The Eras Tour                    20 non-null     float64
 33  cat__Tour title_The Formation World Tour         20 non-null     float64
 34  cat__Tour title_The MDNA Tour                    20 non-null     float64
 35  cat__Tour title_The Monster Ball Tour            20 non-null     float64
 36  cat__Tour title_The Mrs. Carter Show World Tour  20 non-null     float64
 37  cat__Tour title_The Red Tour                     20 non-null     float64
 38  cat__Tour title_The Truth About Love Tour        20 non-null     float64
dtypes: float64(39)
memory usage: 6.2 KB
None

,num__Rank,num__Peak,num__All Time Peak,num__Shows,num__Average gross,num__start_year,num__end_year,num__tour_duration_years,num__Actual gross,num__Adjusted gross (in 2022 dollars),...,cat__Tour title_Summer Carnival,cat__Tour title_Taking Chances World Tour,cat__Tour title_The 1989 World Tour,cat__Tour title_The Eras Tour,cat__Tour title_The Formation World Tour,cat__Tour title_The MDNA Tour,cat__Tour title_The Monster Ball Tour,cat__Tour title_The Mrs. Carter Show World Tour,cat__Tour title_The Red Tour,cat__Tour title_The Truth About Love Tour
0,-1.647509,-2.0,-2.534309,-0.833030,3.084581,1.669789,1.789454,0.206529,3.229302,2.954204,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-1.474087,-2.0,-0.490511,-0.833030,2.003678,1.669789,1.597040,-1.170328,1.915396,1.598088,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-1.300665,-2.0,-2.534309,-0.385662,0.335223,-1.067570,-1.096762,0.206529,0.807567,1.468185,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.127243,0.5,0.735767,0.709618,-0.356706,0.757336,0.827382,0.206529,0.717655,0.751035,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.953821,0.5,0.122628,-0.879309,0.845252,0.757336,0.634968,-1.170328,0.378842,0.399429,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,-0.780399,0.5,0.735767,-0.339383,-0.078267,-0.337608,-0.519519,-1.170328,0.112932,0.305501,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,-0.606977,0.5,0.122628,0.323956,-0.480485,-1.067570,-1.096762,0.206529,-0.052182,0.257774,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,-0.433555,0.5,0.122628,-0.941015,0.453418,0.392355,0.250139,-1.170328,-0.209138,-0.214186,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,-0.260133,0.5,0.122628,-0.385662,-0.236042,0.209864,0.057724,-1.170328,-0.246445,-0.235296,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,-0.086711,-2.0,0.122628,3.316693,-0.940669,-2.162513,-1.866420,2.960242,-0.577219,-0.299414,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.086711,0.5,2.370805,1.434663,-0.788634,-0.885079,-0.711934,1.583385,-0.397394,-0.329048,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11,0.260133,0.5,0.122628,0.339383,-0.601970,-0.155117,-0.134690,0.206529,-0.386237,-0.411002,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12,0.433555,0.5,0.122628,-0.771324,-0.149131,-1.432551,-1.674006,-1.170328,-0.616597,-0.421744,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.606977,0.5,0.122628,-1.064427,0.772916,1.669789,1.789454,0.206529,-0.199192,-0.584431,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.780399,0.5,0.122628,0.632486,-0.718258,0.027374,0.057724,0.206529,-0.550967,-0.623334,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.953821,0.5,0.122628,0.493647,-0.734953,-0.155117,-0.134690,0.206529,-0.682226,-0.788645,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,1.127243,0.5,0.122628,-0.185118,-0.602245,-0.337608,-0.327105,0.206529,-0.774108,-0.882691,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1.300665,0.5,0.122628,-0.431941,-0.500644,0.209864,0.250139,0.206529,-0.775421,-0.926868,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,1.474087,0.5,0.122628,0.169691,-0.707688,0.392355,0.442553,0.206529,-0.789203,-0.944214,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,1.647509,0.5,0.122628,-0.370235,-0.599375,-0.155117,-0.134690,0.206529,-0.905367,-1.073343,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0